config/routes.rb
Bns::Application.routes.draw do
	resources :events do
		member do
			post 'join' => 'events#join'
			post 'quit' => 'events#quit'
		end

		collection do
			get 'joined' => 'events#joined'
			post 'show_participants' => 'events#show_participants'
		end
	end

	resources :user_events, only: [:create, :destroy]

	scope '/student' do
		resources :profile 
		resources :education_profile
	end

  devise_for :admins
	devise_for :students, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout' }

	root to: 'home#index'
	

end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :school_name, :start_place, :end_place, :event_date, 
									:start_time, :end_time, :max_student, :allowance_claim,
									:agency_in_charge, :backup_student, :hidden

	validates :school_name, :event_date, :start_time, :end_time, presence: :true

	validate :end_time_cannot_be_earlier_than_start_time

	has_many :user_events, dependent: :destroy
	has_many :users, through: :user_events

	before_save :default_values

	default_scope order('event_date DESC')

	# Set default values if nothing has input for max and backup student
	def default_values
		self.max_student ||= 0
		self.backup_student ||= 0
	end

	# Get event index by user type
	def self.get_event(user, page)
		if user.is_a? Student
			return Event.where(hidden: false).paginate(page: page)
		else
			return Event.paginate(page: page)
		end
	end

	# overall seats required
	def total_student
		max_student + backup_student
	end

	# show how many seats available, show full if left 0
	def seats_available
		available = total_student - UserEvent.joined_students_count(self.id)

		if available > 0
			available
		else
			"FULL"
		end
	end

	# status for current event, for css styling
	def join_status(user)
    userevent = UserEvent.where(event_id: self.id, user_id: user.id).first
    if userevent
      userevent.join_status ? "joined" : (is_expired? ? "expired" : "nojoin")
    else
      "nojoin"
    end
	end

	# student view of seats available
	def seats_available_over_total
		"#{seats_available} / #{total_student}"
	end

	def event_header
		"#{event_date} #{school_name}"
	end

	# admin view of seats available
	def seats_available_over_max_backup
		"#{seats_available} / #{max_student} + #{backup_student}"
	end

	# determine if an event is expired
	def is_expired?
		self.event_date < DateTime.now
	end

	# determine if an event is hidden by admin
	def is_hidden?
		self.hidden
	end

	# validate end time cannot be earlier than start time 
	def end_time_cannot_be_earlier_than_start_time
		if end_time && start_time 
			if end_time < start_time
				errors.add(:end_time, "End time should not be earlier than start time.")
			end
		end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :custom_user_auth, :profile_must_completed
	before_filter :must_be_admin, only: [ :new, :edit, :destroy, :create, :update ]

  def index
    @events = Event.get_event((current_student || current_admin), params[:page])
  end

=begin
	def show
		@event = Event.find params[:id]
		@action = @event.event_action(current_student)
	end
=end

	def new
		@event = Event.new 
	end

	# To show the student's joined events
	def joined
		@user_events = @events = current_student.events.where(user_events: { join_status: true }).paginate(page: params[:page])
	end

	def create
		@event = Event.new params[:event]
		if @event.save
			redirect_to events_path, notice: "Event is successfully created."
		else
			render "new"
		end
	end

	def edit
		@event = Event.find params[:id]
	end

	def update
		@event = Event.find params[:id]
		if @event.update_attributes params[:event]
			flash.now[:notice] = "Event has been successfully updated."
			render "edit"
		else
			# flash.now[:error] = "Event failed to update."
			render "edit"
		end
	end

	def destroy
		@event = Event.find params[:id]
		if @event.destroy
			redirect_to root_path, notice: "Event has been successfully deleted."
		else 
			redirect_to root_path, error: "Event failed to delete."
		end
	end

	def join
    @userevent = UserEvent.where(user_id: current_student.id, event_id: params[:id]).first

		respond_to do |format|
      unless @userevent
        @userevent = current_student.user_events.build(event_id: params[:id])
        if @userevent.save
          flash.now[:notice] = "You have successfully joined the event."
          format.html { redirect_to :back, notice: "You have successfully joined the event." }
          format.js
        else
          format.html { redirect_to :back, alert: @userevent.errors.full_messages.first }
          format.js { render "fail_join.js.erb", userevent: @userevent }
        end
      else
        @userevent.assign_attributes(join_status:true)
        if @userevent.save
          flash.now[:notice] = "You have successfully joined the event."
          format.html { redirect_to :back, notice: "You have successfully joined the event." }
          format.js
        else
          format.html { redirect_to :back, alert: @userevent.errors.full_messages.first }
          format.js { render "fail_join.js.erb", userevent: @userevent }
        end
      end
		end
	end

	def quit
    @userevent = UserEvent.where(user_id: current_student.id, event_id: params[:id]).first

		respond_to do |format|
      @userevent.assign_attributes(join_status:false)
      if @userevent.save
        flash.now[:notice] = "You have quit the event."
        format.html { redirect_to :back, notice: "You have quit the event." }
        format.js
      else
        format.html { redirect_to :back, alert: @userevent.errors.full_messages.first }
        format.js { render "fail_join.js.erb", userevent: @userevent }
      end
		end
	end

	def show_participants
		@events = Event.find params[:event_ids]
    if @events.count > 1
      render template: "events/admin/show_multi_events_participants"
    else
      #@userevents = @events.first.user_events.where(join_status: true)
			@userevents = UserEvent.show_participants(@events)
      render template: "events/admin/show_single_event_participants"
    end
	end

	private
		def must_be_admin
			unless admin_signed_in?
				redirect_to root_path
				return
			end
		end
end

app/helpers/event_helper.rb
module EventHelper
	def formatted_date(d)
		d.strftime("%d %b %Y (%a)")
	end

	def formatted_time(t)
		t.strftime("%H:%M")
	end

	def display_joined(str)
		str == "joined" ? "Joined" : "Not yet join"
	end

	def join_action(str)
		str == "joined" ? "Quit" : "Join"
	end

	def get_join_status(event)
		if student_signed_in?
			event.join_status(current_student)
		else
			if event.is_expired?
				"expired"
			elsif event.is_hidden?
				"is-hidden"
			elsif !event.is_hidden? && event.seats_available == "FULL"
				"published full"
			else
				"published"
			end
		end
	end

	def get_all_users(events)
		users = []

		# To retrieve all users with union method
		for event in events
      users = users | event.users.where(user_events: { join_status: true })
		end

		return users
	end

	# Get total participants joined for specific number of days
	def day_total(users, events, days)
		total = 0

		for user in users
      total += ((( user.events.where(user_events: { join_status: true }) & events ).count) == days) ? 1 : 0
		end

		return total
	end

	# Customed dynamic join quit event button
	def join_quit_button(status, event)
		if status == "joined" 
			button_to("Quit Event", quit_event_path(event), 
			{ confirm: "Are you sure to quit this event?",
				remote: true, 
				disabled: (event.seats_available == "FULL" && status != "joined") || event.is_expired? }) 
		else 
			button_to("Join Event", join_event_path(event),
			{ remote: true, 
				disabled: (event.seats_available == "FULL" && status != "joined") || event.is_expired? }) 
		end 
	end
end

app/views/events/_admin_event_table.html.erb
<div id="notice" style="display: none;"></div>

<% content_for :head do %>
	<%= stylesheet_link_tag "event" %>
<% end %>

<table class="bordered" id="event_table">
	<thead>
		<tr>
			<%= content_tag :th, "No.", 
					{ abbr: :Number, 
						scope: :col, 
						colspan: 2 } %>
			<th scope="col" abbr="Date">Event Date</th>
			<th scope="col" abbr="StartT">Start Time</th>
			<th scope="col" abbr="EndT">End Time</th>
			<th scope="col" abbr="School">School Name</th>
			<th scope="col" abbr="StartP">Start Place</th>
			<th scope="col" abbr="EndP">End Place</th>
      <th scope="col" abbr="AIC">Agency In Charge</th>
			<th scope="col" abbr="Allowance">Allowance Claim</th>
			<th scope="col" abbr="Seats">Seats Avail. / Total</th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<tbody>
		<%= render @events %>
	</tbody>
</table>

app/views/events/_event_table.html.erb
<div id="notice" style="display: none;"></div>

<% content_for :head do %>
	<%= stylesheet_link_tag "event" %>
<% end %>

<table class="bordered" id="event_table">
	<thead>
		<tr>
			<%= content_tag :th, "No.", 
					{ abbr: :Number, 
						scope: :col, 
						colspan: admin_signed_in? ? 2 : 1 } %>
			<th scope="col" abbr="Date">Event Date</th>
			<th scope="col" abbr="StartT">Start Time</th>
			<th scope="col" abbr="EndT">End Time</th>
			<th scope="col" abbr="School">School Name</th>
			<th scope="col" abbr="AIC">Agency In Charge</th>
			<th scope="col" abbr="StartP">Start Place</th>
			<th scope="col" abbr="EndP">End Place</th>
			<th scope="col" abbr="Allowance">Allowance Claim</th>
			<th scope="col" abbr="Seats">Seats Avail. / Total</th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<tbody>
		<%= render @events %>
	</tbody>
</table>

app/views/events/_form.html.erb
<%= simple_form_for(@event, html: { class: :"form-horizontal" }) do |f| %>
	<%= f.input :school_name %>

	<%= f.input :start_place %>

	<%= f.input :end_place %>

	<%= f.input :event_date, wrapper_html: { id: :"event_datepicker" }, wrapper: :append do %>
		<%= f.input_field :event_date, 
				value: :"#{@event.event_date.blank? ? "" : @event.event_date.strftime("%d-%m-%Y")}", 
				as: :string, "data-format" => "dd-MM-yyyy" %>
		<%= content_tag :span, 
				content_tag(:i, "", data: { time_icon: :"icon-time", date_icon: :"icon-calendar" }), 
				class: :"add-on" %>
	<% end %>

	<%= f.input :start_time, wrapper_html: { id: :"event_timepicker" }, wrapper: :append do %>
		<%= f.input_field :start_time, 
				value: :"#{@event.start_time.blank? ? "" : formatted_time(@event.start_time)}", 
				as: :string, "data-format" => "hh:mm" %>
		<%= content_tag :span, 
				content_tag(:i, "", data: { time_icon: :"icon-time", date_icon: :"icon-calendar" }), 
				class: :"add-on" %>
	<% end %>

	<%= f.input :end_time, wrapper_html: { id: :"event_timepicker" }, wrapper: :append do %>
		<%= f.input_field :end_time, 
				value: :"#{@event.end_time.blank? ? "" : formatted_time(@event.end_time)}", 
				as: :string, "data-format" => "hh:mm" %>
		<%= content_tag :span, 
				content_tag(:i, "", data: { time_icon: :"icon-time", date_icon: :"icon-calendar" }), 
				class: :"add-on" %>
	<% end %>

	<%= f.input :max_student %>

	<%= f.input :backup_student %>

	<%= f.input :allowance_claim %>

	<%= f.input :agency_in_charge %>

	<%= f.input :hidden %>

	<div class="form-actions">
		<%= f.button :submit, class: :"btn-success" %>
		<%= link_to "Cancel", events_path, class: :"btn btn-danger" %>
	</div>
<% end %>

<% content_for :head do %>
	<%= javascript_include_tag "bootstrap-datetimepicker.min", "event" %>
	<%= stylesheet_link_tag "bootstrap-datetimepicker.min" %>
<% end %>

app/views/events/_show_multi_events_participants.html.erb
<table class="bordered" id="days_joined" style="width: 20%;">
	<thead>
		<tr>
			<th>Days</th>
			<th>Number of participants</th>
		</tr>
	</thead>
	<tbody>
		<%= render 'days_joined', events: @events, users: get_all_users(@events) %>
	</tbody>
</table>

<br /><br />

<table class="bordered" id="participants_table">
	<thead>
		<tr>
			<th>Participants</th>
			<% for event in @events %>
				<th><%= event.event_header %></th>
			<% end %>
			<th>Counts</th>
		</tr>
	</thead>
	<tbody>
		<%= render "multi_events", events: @events %>
	</tbody>
	<tfoot>
		<th>Total Participants</th>
		<% for event in @events %>
			<th><%= event.users.count %></th>
		<% end %>
		<th></th>
	</tfoot>
</table>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form' %>

app/views/events/fail_join.js.erb
alert("<%= @userevent.errors.full_messages.first %>");

<% if @userevent.update_count < APP_CONFIG["flood_count"] %>
  document.location.reload(true)
<% end %>

app/views/events/index.html.erb
<h1 id="title">Recent Events</h1>

<% if admin_signed_in? %>
	<%= form_tag show_participants_events_path do %>
    <div id="events"><%= render "events/admin/event_table" %></div>
		<div class="form-actions">
			<%= submit_tag "Show Participants", class: :"btn btn-primary" %>
		</div>
	<% end %>
<% else %>
  <div id="events"><%= render "events/student/event_table" %></div>
<% end %>

app/views/events/index.js.erb
$("#events").html("<%= escape_javascript(render("events/#{admin_signed_in? ? "admin":"student"}/event_table")) %>");

app/views/events/join.js.erb
<% broadcast "/events/join" do %>
	$("#<%= dom_id @userevent.event %> #seats_available").html("<%= @userevent.event.seats_available_over_total %>");
<% end %>

var event_row = $("#<%= dom_id @userevent.event %>");

event_row.removeClass("nojoin").addClass("joined");

event_row.children("#join_status").html("Joined");

event_row.children("#join_button").html("<%= 
	escape_javascript(button_to "Quit Event", 
	quit_event_path(@userevent.event), confirm: "Are you sure to quit this event?", 
	remote: true) %>");

function renderNotice() {
  $("#notice").html("<%= escape_javascript(render("layouts/messages")) %>");
}

if ($("#notice").is(":hidden")) {
  renderNotice();
  $("#notice").slideDown(500);
} else {
  $("#notice").hide(500, function() {
    renderNotice();
    $(this).slideDown(500);
  });
}

app/views/events/joined.html.erb
<h1>Joined Events</h1>

<div id="events">
	<% unless @events.empty? %>
    <%= render "events/student/event_table" %>
	<% else %>
		<%= content_tag :p, "You have not joined any events yet." %>
	<% end %>
</div>

app/views/events/new.html.erb
<h1>New Event Details</h1>

<%= render 'form' %>

app/views/events/quit.js.erb
<% broadcast "/events/join" do %>
	$("#<%= dom_id @userevent.event %> #seats_available").html("<%= @userevent.event.seats_available_over_total %>");
<% end %>

var event_row = $("#<%= dom_id @userevent.event %>");

event_row.removeClass("joined").addClass("nojoin");

event_row.children("#join_status").html("Not yet join");

event_row.children("#join_button").html("<%= 
	escape_javascript(button_to "Join Event", 
	join_event_path(@userevent.event), 
	remote: true) %>");

function renderNotice() {
  $("#notice").html("<%= escape_javascript(render("layouts/messages")) %>");
}


if ($("#notice").is(":hidden")) {
  renderNotice();
  $("#notice").slideDown(500);
} else {
  $("#notice").hide(500, function() {
    renderNotice();
    $(this).slideDown(500);
  });
}

app/views/events/show.html.erb
<h1>Event details:</h1>

<table border="1" bordercolor="#FFCC00" style="background-color:#FFFFCC" width="50%" cellpadding="3" cellspacing="3">
	<tr>
		<td width="30%">School Name:</td>
		<td><%= @event.school_name %></td>
	</tr>

	<tr>
		<td>Starting point:</td>
		<td><%= @event.start_place %></td>
	</tr>
	
	<tr>
		<td>Ending point:</td>
		<td><%= @event.end_place %></td>
	</tr>

	<tr>
		<td>Event Date:</td>
		<td><%= formatted_date(@event.event_date) %></td>
	</tr>

	<tr>
		<td>Start Time:</td>
		<td><%= formatted_time(@event.start_time) %></td>
	</tr>
	
	<tr>
		<td>End Time:</td>
		<td><%= formatted_time(@event.end_time) %></td>
	</tr>

	<tr>
		<td>Agency In Charge:</td>
		<td><%= @event.agency_in_charge %></td>
	</tr>

	<tr>
		<td>Allowance Claiming:</td>
		<td><%= @event.allowance_claim %></td>
	</tr>

	<tr>
		<td>Max student:</td>
		<td><%= @event.total_student %></td>
	</tr>

	<% if admin_signed_in? %>
		<tr>
			<td>Backup student</td>
			<td><%= @event.backup_student %></td>
		</tr>
	<% end %>

	<tr>
		<td>Seats available:</td>
		<td><%= @event.seats_available %></td>
	</tr>
</table>
<%= render 'event_actions' %>