config/routes.rb
Bns::Application.routes.draw do
	resources :events do
		member do
			post 'join' => 'events#join'
			post 'quit' => 'events#quit'
		end

		collection do
			get 'joined' => 'events#joined'
			post 'show_participants' => 'events#show_participants'
		end
	end

	resources :user_events, only: [:create, :destroy]

	scope '/student' do
		resources :profile 
		resources :education_profile
	end

  devise_for :admins
	devise_for :students, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout' }

	root to: 'home#index'
	

end

app/views/layouts/_admin_actions.html.erb
<li>
	<%= link_to 'Logout', destroy_admin_session_path %>
</li>
<li>
	<%= link_to "New Event", new_event_path %>
</li>

app/views/layouts/_anonymous_actions.html.erb
<li>
	<%= link_to 'Login', new_student_session_path %>  
</li>
<li>
	<%= link_to 'Sign up', new_student_registration_path %>
</li>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
	<div class="alert alert-block alert-error fade in">
		<a class="close" data-dismiss="alert"><i class="icon-remove"></i></a>
		<b>Errors:</b>
		<ul>
			<% model.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %> fade in">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "B&S Home", root_path, :class => 'brand' %>
<ul class="nav">
	<% if student_signed_in? %>
		<%= render 'layouts/student_actions' %>
	<% elsif admin_signed_in? %>
		<%= render 'layouts/admin_actions' %>
	<% else %>
		<%= render 'layouts/anonymous_actions' %>
	<% end %>
</ul>
<ul class="nav pull-right">
  <li class="navbar-text"><%= greet_message %></li>
</ul>

app/views/layouts/_student_actions.html.erb
<li>
	<%= link_to 'Logout', destroy_student_session_path %>
</li>
<li>
	<%= link_to "Profile", profile_index_path %>
</li>
<li>
	<%= link_to "Joined Events", joined_events_path %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Brother & Sister Programme Malaysia</title>
		<%= stylesheet_link_tag    "application", "event",	
				"http://necolas.github.com/normalize.css/2.1.0/normalize.css" %>
        <%= javascript_include_tag "application", "#{APP_CONFIG["faye_url"]}/faye.js" %>
		<%= yield(:head) %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<header class="navbar navbar-fixed-top">
			<nav class="navbar-inner">
				<div class="container">
					<%= render 'layouts/navigation' %>
				</div>
			</nav>
		</header>

		<div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <div id="notice" style="display: none; padding: .1em 0"></div>
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->

	</body>
	<script type="text/javascript" charset="utf-8">
		$(function() {
			var client = new Faye.Client("<%= escape_javascript(APP_CONFIG["faye_url"]) %>/faye");
				client.subscribe("/events/join", function(data) {
					eval(data);
			});
		});
	</script>
</html>